### ISSUE TITLE
Text alignment fix

### ISSUE THREAD

**Issue by acurrieclark** [cantoo-scribe/html2canvas#3]
I thought I would link here for you to take a look before I post a PR: https://github.com/acurrieclark/html2canvas

There are 2 options: one on the main branch and another on a branch called `only-change-text`.

On main, I have changed the signature of `renderTextWithLetterSpacing` so that it takes the styles instead of the baseline property. This works for my purposes, but the are multiple places the function is called, and I don't know how the baseline is applied from the paths which I can't test.

The `only-change-text` path just updates the path I can test, and keeps the signature the same. Instead, it swaps out the `baseline` argument for the `fontSize` value.

If you could take a look and let me what you think, I will submit an appropriate PR.

**Comment by Sharcoux** [comment]
@acurrieclark Your change seems ok, except that it doesn't take the lineHeight in consideration. I don't know the project very well, but it's likely a problem.

**Comment by acurrieclark** [comment]
That was my instinct too. It seemed that line height would be important. I have tried it with a number of line heights thought, and it doesn't seem to make any difference.

My assumption is that the `top` property already accounts for the line height. In my case it handles one word at a time, not whole lines anyway.

**Comment by Sharcoux** [comment]
Check with line-height above and below the size of the font-size. If you still get the expected result in both cases, then, yes, it's probably fine.

**Comment by Sharcoux** [comment]
@acurrieclark can you tell me the result of your test? If it's fine in both cases I'll merge

**Comment by Sharcoux** [comment]
@acurrieclark would you mind opening a pull request of your changes so I can merge them?

**Comment by acurrieclark** [comment]
Sorry for the delay in responding. Finally got round to running a quick line height test and it all seems to work as expected:

https://github.com/cantoo-scribe/html2canvas/assets/1306728/744d0270-ba06-4e09-91a0-2827e185c29f

Example shows 4 divs of different line heights. "Print" then runs html2canvas on the parent div and adds the svg below it.

I'll get a PR sorted

**Comment by Sharcoux** [comment]
Released in 1.5.8
